---
abstract: 
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EventReactor
no_index:
  directory:
    - inc
    - t
resources:
  repository: git@github.com:tupinek/event_reactor.git
version: 0.0001
